In [33]:
import pandas as pd

# Occupied dataset

In [34]:
occupied_dataset = pd.read_csv("../data/raw/occupied_puf_23.csv")
occupied_dataset

,CONTROL,TENURE,HHSIZE,HH62PLUS,HHUNDER18,HHUNDER6,HHFIRSTMOVEIN,HHDEAR,HHDEYE,HHDREM,...,FW71,FW72,FW73,FW74,FW75,FW76,FW77,FW78,FW79,FW80
0,12130002,2,4,2,1,2,2007,2,2,2,...,442.455446,127.631770,711.527866,132.998833,709.589086,130.988565,736.863209,129.455196,762.451636,119.404255
1,12130005,1,2,1,2,2,2003,2,2,2,...,169.052548,553.284761,942.616620,164.975190,931.214014,559.255649,554.254696,560.187235,161.939232,567.640705
2,12130008,1,2,2,2,2,2022,2,2,2,...,239.068885,234.129431,71.519095,399.007919,71.703011,234.722388,410.574605,70.158697,393.432862,246.590232
3,12130010,1,1,2,2,2,2021,2,2,2,...,230.859408,224.223475,224.530093,232.675383,379.403388,66.640274,222.069717,387.334049,225.783637,232.247668
4,12130011,2,1,2,2,2,2021,1,1,1,...,537.958596,521.546224,888.184005,542.202939,149.320506,530.269565,524.148922,518.288581,900.353246,532.630520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8771,12158886,1,2,1,2,2,2013,1,1,1,...,249.642410,429.093077,264.682886,260.675178,255.321122,77.789638,253.021151,439.918701,259.420088,258.679813
8772,12158888,1,3,2,1,2,2018,2,2,2,...,177.331859,174.204259,167.746866,587.990824,592.679480,173.258906,170.266419,575.221657,171.783096,172.634492
8773,12158891,2,5,2,1,2,2007,2,2,2,...,1016.971770,568.040423,582.367243,585.770664,594.786202,580.336959,165.784492,983.903069,172.660540,571.598400
8774,12158893,1,2,2,2,2,2022,2,2,2,...,415.471520,71.921377,239.770131,244.641758,401.938011,243.534240,239.737898,71.827585,240.138474,411.038052
8775,12158897,1,1,1,2,2,2012,2,2,2,...,426.166251,73.620733,264.682886,260.675178,435.860419,265.590437,74.108179,257.698409,259.420088,258.679813

In [35]:
housing_quality_columns = [
    "NOHEAT", # Indicates whether there was any heating breakdown in the previous winter, even if it was for less than 6 hours. 
    "NOHEAT_NUM", # Indicates the number of times the unit has a heating breakdown for 6 or more hours in the previous winter.
    "NOHOTWATER", # Indicates whether there was no hot water for at least 6 hours anytime in the previous year. 
    "LEAKS", # Indicates whether there were any leaks from outside the unit in the past year
    "MOLD", # Indicates whether there has been any mold in the unit in the previous year. 
    "MUSTY", # Indicates the frequency that the occupant smelled musty or moldy smells in the unit in the previous year. 
    "ELEVATOR_BROK", # Indicates whether any elevator in the building was not working for 6 or more hours in the previous year
    "ELEVATOR_ALLBROK", # Indicates whether all elevators in the building were not working for 6 or more hours in the previous year. 
    "RODENTS_UNIT", # Indicates if there was any evidence of mice or rats in the unit in the past three months. 
    "RODENTS_BUILD", # Indicates if there was any evidence of mice or rats in the building where the unit is located in the past three months. 
    "TOILET_BROK", # Indicates that none of the toilets in the unit were working for 6 hours or more in the previous three months. 
    "ROACHES_NUM", # Indicates the number of roaches the occupant(s) saw on a typical day in the last month. 
    "WALLHOLES", # Indicates if there were holes in the walls or ceiling inside the unit at the time of the NYCHVS interview. 
    "FLOORHOLES", # Indicates if there were holes in the floors inside the unit at the time of the NYCHVS interview.
    "PEELPAINT", # Indicates if there was any broken plaster or peeling paint inside the unit at the time of the NYCHVS interview.
    "PEELPAINT_LARGE", # Indicates if any section of broken plaster or peeling paint inside the unit at the time of the NYCHVS interview was at least 8 1/2 x 11 inches in size. 
    "HPROBCOUNT" # Count of select housing problems in housing unit including: 1+ heating breakdown of 6 hours or more, insufficient heat, leaks, rodents in the unit or building, toilet(s) not working, holes in walls or floors, large section(s) of peeling paint or broken plaster.
    ]

In [36]:
housing_cost_columns = [
    'RENT_AMOUNT' # Monthly rent due last month, inclusive of any fees paid separately and regardless of whether this amount was paid by the tenant(s) or others on behalf of the tenant. 
]

In [37]:
income_columns = [
    'HHINC_REC1' # Total household income from all persons and all sources of income in 2022.
]

In [38]:
subsidy_programs_columns = [
    'RENTASSIST', # Respondent reported receiving one or more of the following types of assistance: Section 8/Housing Choice Voucher, Shelter Allowance, City FHEPS, SCRIE, DRIE, or another city, state, or federal program that pays all or part of the rent.
    'RENTASSIST_VOUCHER', # Household reported having Section 8/Housing Choice Voucher
]

In [39]:
household_characteristics_columns = [
    'HHSIZE', # Indicates the number of current occupants living in the housing unit. 
    'HH62PLUS', # Indicates whether there is one or more person age 62 or older living in the housing unit.
    'HHUNDER18' # Indicates whether there is one or more person under age 18 in living in the housing unit.
]

In [40]:
unit_level_survey_weight_columns = [
    'FW'
]

In [41]:
replicate_weights_columns = [f"FW{i}" for i in range(1, 81)]

In [42]:
occupied_dataset_subset = occupied_dataset[['CONTROL'] + housing_quality_columns + housing_cost_columns + income_columns + subsidy_programs_columns + household_characteristics_columns + unit_level_survey_weight_columns + replicate_weights_columns]
occupied_dataset_subset

,CONTROL,NOHEAT,NOHEAT_NUM,NOHOTWATER,LEAKS,MOLD,MUSTY,ELEVATOR_BROK,ELEVATOR_ALLBROK,RODENTS_UNIT,...,FW71,FW72,FW73,FW74,FW75,FW76,FW77,FW78,FW79,FW80
0,12130002,2,-2,1,2,2,5,1,1,2,...,442.455446,127.631770,711.527866,132.998833,709.589086,130.988565,736.863209,129.455196,762.451636,119.404255
1,12130005,2,-2,2,2,2,5,2,-2,2,...,169.052548,553.284761,942.616620,164.975190,931.214014,559.255649,554.254696,560.187235,161.939232,567.640705
2,12130008,2,-2,3,2,2,5,2,-2,2,...,239.068885,234.129431,71.519095,399.007919,71.703011,234.722388,410.574605,70.158697,393.432862,246.590232
3,12130010,2,-2,2,2,2,5,2,-2,2,...,230.859408,224.223475,224.530093,232.675383,379.403388,66.640274,222.069717,387.334049,225.783637,232.247668
4,12130011,2,-2,2,2,2,5,1,2,2,...,537.958596,521.546224,888.184005,542.202939,149.320506,530.269565,524.148922,518.288581,900.353246,532.630520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8771,12158886,2,-2,2,2,2,5,1,2,1,...,249.642410,429.093077,264.682886,260.675178,255.321122,77.789638,253.021151,439.918701,259.420088,258.679813
8772,12158888,2,-2,2,2,2,5,-2,-2,2,...,177.331859,174.204259,167.746866,587.990824,592.679480,173.258906,170.266419,575.221657,171.783096,172.634492
8773,12158891,2,-2,2,2,2,5,-2,-2,2,...,1016.971770,568.040423,582.367243,585.770664,594.786202,580.336959,165.784492,983.903069,172.660540,571.598400
8774,12158893,-3,-3,-3,-3,-3,-3,-3,-3,1,...,415.471520,71.921377,239.770131,244.641758,401.938011,243.534240,239.737898,71.827585,240.138474,411.038052
8775,12158897,2,-2,2,2,2,5,2,-2,2,...,426.166251,73.620733,264.682886,260.675178,435.860419,265.590437,74.108179,257.698409,259.420088,258.679813

In [43]:
occupied_dataset_subset.to_csv("../data/processed/occupied_dataset_subset.csv", index=False)

# Persons dataset

In [44]:
persons_dataset = pd.read_csv("../data/raw/person_puf_23.csv")
persons_dataset

,CONTROL,LNO,RELATION_P,AGE_REC_P,GENDER_P,MARITALSTAT_P,SPOUSE_RES_P,SPOUSE_LOC_P,SPOUSE_P,LNSPOUSE_P,...,PW71,PW72,PW73,PW74,PW75,PW76,PW77,PW78,PW79,PW80
0,12130002,3,3,13,1,-2,-2,-2,-2,-2,...,383.321453,124.489828,663.322538,118.583212,706.027375,110.421141,688.758431,122.383513,691.487193,121.200499
1,12130002,1,0,43,1,1,1,-2,1,2,...,442.455446,127.631770,711.527866,132.998833,709.589086,130.988565,736.863209,129.455196,762.451636,119.404255
2,12130002,4,3,7,1,-2,-2,-2,-2,-2,...,383.321453,124.489828,663.322538,118.583212,706.027375,110.421141,688.758431,122.383513,691.487193,121.200499
3,12130002,2,1,42,2,-2,-2,-2,1,1,...,442.455446,127.631770,711.527866,132.998833,709.589086,130.988565,736.863209,129.455196,762.451636,119.404255
4,12130005,2,1,63,1,-2,-2,-2,1,1,...,169.052548,553.284761,942.616620,164.975190,931.214014,559.255649,554.254696,560.187235,161.939232,567.640705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20453,12158891,4,3,19,1,-2,-2,-2,3,-2,...,1039.448893,541.407265,562.638856,637.448013,502.108532,629.914632,156.312966,1001.488482,154.037228,535.392556
20454,12158891,2,1,51,1,-2,-2,-2,1,1,...,1016.971770,568.040423,582.367243,585.770664,594.786202,580.336959,165.784492,983.903069,172.660540,571.598400
20455,12158893,2,10,29,1,-2,-2,-2,3,-2,...,321.550158,72.122335,220.485963,221.941051,366.956168,225.211468,238.324811,58.472787,248.717889,360.002113
20456,12158893,1,0,28,1,5,-2,-2,3,-2,...,415.471520,71.921377,239.770131,244.641758,401.938011,243.534240,239.737898,71.827585,240.138474,411.038052
20457,12158897,1,0,75,2,-1,-2,-2,3,-2,...,426.166251,73.620733,264.682886,260.675178,435.860419,265.590437,74.108179,257.698409,259.420088,258.679813

In [45]:
racial_classification_columns = [
    'RACE_P', # Indicates the person's race. 
    'RACEETH_P' # Indicates the person's race and ethnicity, combined into a single variable. 
]

In [46]:
citizenship_status_columns = [
    'PLACEBORN_NYC_P', # Indicates where the person was born. 
    'PLACEBORN_MOTHER_P', # Indicates the person's mother's place of birth, by region. 
    'PLACEBORN_FATHER_P', # Indicates the person's father's place of birth, by region.
]

In [47]:
marrital_status_columns = [
    "RELATION_P", # Indicates the relationship of each co-resident person in the household to the respondent.
    "MARITALSTAT_P", # Marital status of the respondent. This item is not collected for other persons in the household.
    "SPOUSE_RES_P", # Indicates where the spouse of the respondent lives. 
    "SPOUSE_P", # Indicates if the person has a spouse or partner in the household.
    "LNSPOUSE_P", # This variable indicates the line number (LNO) of co-resident spouse. 
    "LNPARTNER_P" # This variable indicates the line number (LNO) of co-resident partner. 
]

In [48]:
person_level_survey_weight_columns = [
    'PW'
]

In [49]:
persons_replicate_weights_columns = [f"PW{i}" for i in range(1, 81)]

In [50]:
person_dataset_subset = persons_dataset[['CONTROL'] + racial_classification_columns + marrital_status_columns + person_level_survey_weight_columns + persons_replicate_weights_columns]
person_dataset_subset

,CONTROL,RACE_P,RACEETH_P,RELATION_P,MARITALSTAT_P,SPOUSE_RES_P,SPOUSE_P,LNSPOUSE_P,LNPARTNER_P,PW,...,PW71,PW72,PW73,PW74,PW75,PW76,PW77,PW78,PW79,PW80
0,12130002,1,1,3,-2,-2,-2,-2,-2,406.212770,...,383.321453,124.489828,663.322538,118.583212,706.027375,110.421141,688.758431,122.383513,691.487193,121.200499
1,12130002,1,1,0,1,1,1,2,-2,434.673470,...,442.455446,127.631770,711.527866,132.998833,709.589086,130.988565,736.863209,129.455196,762.451636,119.404255
2,12130002,1,1,3,-2,-2,-2,-2,-2,406.212770,...,383.321453,124.489828,663.322538,118.583212,706.027375,110.421141,688.758431,122.383513,691.487193,121.200499
3,12130002,1,1,1,-2,-2,1,1,-2,434.673470,...,442.455446,127.631770,711.527866,132.998833,709.589086,130.988565,736.863209,129.455196,762.451636,119.404255
4,12130005,1,1,1,-2,-2,1,1,-2,555.435361,...,169.052548,553.284761,942.616620,164.975190,931.214014,559.255649,554.254696,560.187235,161.939232,567.640705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20453,12158891,1,1,3,-2,-2,3,-2,-2,569.598977,...,1039.448893,541.407265,562.638856,637.448013,502.108532,629.914632,156.312966,1001.488482,154.037228,535.392556
20454,12158891,1,1,1,-2,-2,1,1,-2,576.899607,...,1016.971770,568.040423,582.367243,585.770664,594.786202,580.336959,165.784492,983.903069,172.660540,571.598400
20455,12158893,1,1,10,-2,-2,3,-2,-2,223.345895,...,321.550158,72.122335,220.485963,221.941051,366.956168,225.211468,238.324811,58.472787,248.717889,360.002113
20456,12158893,1,1,0,5,-2,3,-2,-2,242.169172,...,415.471520,71.921377,239.770131,244.641758,401.938011,243.534240,239.737898,71.827585,240.138474,411.038052
20457,12158897,2,3,0,-1,-2,3,-2,-2,256.429010,...,426.166251,73.620733,264.682886,260.675178,435.860419,265.590437,74.108179,257.698409,259.420088,258.679813

In [51]:
person_dataset_subset.to_csv("../data/processed/person_dataset_subset.csv", index=False)

# All units

In [52]:
all_units_dataset = pd.read_csv("../data/raw/allunits_puf_23.csv")
all_units_dataset

,CONTROL,BORO,OCC,CSR,CONDOCOOP,STORIES,ELEVATOR,UNITS,UNIT_FLOOR,UNIT_ONEPLUSFLIGHT,...,FW71,FW72,FW73,FW74,FW75,FW76,FW77,FW78,FW79,FW80
0,12130002,2,1,2,2,6,1,10,5,2,...,442.455446,127.631770,711.527866,132.998833,709.589086,130.988565,736.863209,129.455196,762.451636,119.404255
1,12130005,3,1,80,2,4,1,6,3,2,...,169.052548,553.284761,942.616620,164.975190,931.214014,559.255649,554.254696,560.187235,161.939232,567.640705
2,12130008,3,1,80,3,7,1,10,5,2,...,239.068885,234.129431,71.519095,399.007919,71.703011,234.722388,410.574605,70.158697,393.432862,246.590232
3,12130010,3,1,80,3,5,1,10,1,2,...,230.859408,224.223475,224.530093,232.675383,379.403388,66.640274,222.069717,387.334049,225.783637,232.247668
4,12130011,3,1,2,2,4,1,8,5,2,...,537.958596,521.546224,888.184005,542.202939,149.320506,530.269565,524.148922,518.288581,900.353246,532.630520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9592,12158886,1,1,32,3,5,1,9,3,2,...,249.642410,429.093077,264.682886,260.675178,255.321122,77.789638,253.021151,439.918701,259.420088,258.679813
9593,12158888,2,1,80,3,1,2,2,1,2,...,177.331859,174.204259,167.746866,587.990824,592.679480,173.258906,170.266419,575.221657,171.783096,172.634492
9594,12158891,5,1,6,3,1,2,2,1,2,...,1016.971770,568.040423,582.367243,585.770664,594.786202,580.336959,165.784492,983.903069,172.660540,571.598400
9595,12158893,3,1,80,3,7,1,10,3,2,...,415.471520,71.921377,239.770131,244.641758,401.938011,243.534240,239.737898,71.827585,240.138474,411.038052
9596,12158897,1,1,32,3,5,1,10,5,2,...,426.166251,73.620733,264.682886,260.675178,435.860419,265.590437,74.108179,257.698409,259.420088,258.679813

In [53]:
housing_type_columns = [
    'CSR', # Classifies the unit as one of several major types of housing based on a combination of information, including the unit's occupancy status and the current occupant(s) tenure, the regulatory status of the unit and building, and the ownership structure of the property.
    'OCC' # Occupancy status of housing unit.
]

In [54]:
property_characteristics_columns = [
    'YEARBUILT', # Year in which the building where the unit is located was built. 
    'UNITS', # Indicates the total number of residential units in the building. In cases where the residential complex includes multiple buildings, this variable does not count units located in other parts of the complex.
    'ROOMS', # Number of rooms, inclusive of bedrooms, in the unit. 
]

In [55]:
location_columns = [
    'BORO', # Borough (county name) where the housing unit is located 
]

In [56]:
unit_level_survey_weight_columns = [
    'FW'
]

In [57]:
replicate_weights_columns = [f"FW{i}" for i in range(1, 81)]

In [58]:
all_units_dataset_subset = all_units_dataset[['CONTROL'] + housing_type_columns + property_characteristics_columns + location_columns + unit_level_survey_weight_columns + replicate_weights_columns]
all_units_dataset_subset

,CONTROL,CSR,OCC,YEARBUILT,UNITS,ROOMS,BORO,FW,FW1,FW2,...,FW71,FW72,FW73,FW74,FW75,FW76,FW77,FW78,FW79,FW80
0,12130002,2,1,5,10,8,2,434.673470,434.673470,433.101582,...,442.455446,127.631770,711.527866,132.998833,709.589086,130.988565,736.863209,129.455196,762.451636,119.404255
1,12130005,80,1,3,6,3,3,555.435361,555.435361,932.333825,...,169.052548,553.284761,942.616620,164.975190,931.214014,559.255649,554.254696,560.187235,161.939232,567.640705
2,12130008,80,1,7,10,4,3,238.775657,238.775657,231.828215,...,239.068885,234.129431,71.519095,399.007919,71.703011,234.722388,410.574605,70.158697,393.432862,246.590232
3,12130010,80,1,4,10,1,3,226.590865,226.590865,219.345692,...,230.859408,224.223475,224.530093,232.675383,379.403388,66.640274,222.069717,387.334049,225.783637,232.247668
4,12130011,2,1,2,8,3,3,526.067721,526.067721,152.723123,...,537.958596,521.546224,888.184005,542.202939,149.320506,530.269565,524.148922,518.288581,900.353246,532.630520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9592,12158886,32,1,10,9,2,1,256.429010,256.429010,75.962910,...,249.642410,429.093077,264.682886,260.675178,255.321122,77.789638,253.021151,439.918701,259.420088,258.679813
9593,12158888,80,1,3,2,6,2,586.284150,586.284150,170.460078,...,177.331859,174.204259,167.746866,587.990824,592.679480,173.258906,170.266419,575.221657,171.783096,172.634492
9594,12158891,6,1,10,2,5,5,576.899607,576.899607,982.037847,...,1016.971770,568.040423,582.367243,585.770664,594.786202,580.336959,165.784492,983.903069,172.660540,571.598400
9595,12158893,80,1,8,10,4,3,242.169172,242.169172,70.692910,...,415.471520,71.921377,239.770131,244.641758,401.938011,243.534240,239.737898,71.827585,240.138474,411.038052
9596,12158897,32,1,8,10,3,1,256.429010,256.429010,442.744285,...,426.166251,73.620733,264.682886,260.675178,435.860419,265.590437,74.108179,257.698409,259.420088,258.679813

In [59]:
all_units_dataset_subset.to_csv("../data/processed/all_units_dataset_subset.csv", index=False)